---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: platform-kubernetes-store
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider:
    kubernetes:
      remoteNamespace: platform-secrets
      server:
        url: https://kubernetes.default.svc
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: platform-secrets
          key: ca.crt
      auth:
        serviceAccount:
          name: eso-kubernetes-store
          namespace: platform-secrets
